import streamlit as st
import pandas as pd
import requests
from fpdf import FPDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np


# 🔑 OMDb API key
OMDB_API_KEY = st.secrets["omdb"]["api_key"]

# ⭐ Initialize favorites in session
if "favorites" not in st.session_state:
    st.session_state["favorites"] = []

# 🎬 Function to fetch poster + ratings + extra metadata
@st.cache_data(show_spinner=False)
def get_movie_data(title):
    url = f"http://www.omdbapi.com/?t={title}&apikey={OMDB_API_KEY}"
    response = requests.get(url).json()

    poster_url = response.get("Poster")
    imdb_rating = response.get("imdbRating", "N/A")
    rt_rating = "N/A"
    for r in response.get("Ratings", []):
        if r["Source"] == "Rotten Tomatoes":
            rt_rating = r["Value"]

    plot = response.get("Plt", "N/A")
    director = response.get("Director", "N/A")
    runtime = response.get("Runtime", "N/A")

    # ✅ Only return values here
    return poster_url, imdb_rating, rt_rating, plot, director, runtime

# 🔍 Function to fetch live suggestions from OMDb
@st.cache_data(show_spinner=False)
def get_movie_suggestions(query):
    url = f"http://www.omdbapi.com/?s={query}&apikey={OMDB_API_KEY}"
    response = requests.get(url).json()
    if response.get("Search"):
        return [movie["Title"] for movie in response["Search"]]
    return []



# 🎥 Free trailer link (opens directly)
def get_trailer_link(title):
    query = title.replace(" ", "+") + "+official+trailer"
    return f"https://www.youtube.com/results?search_query={query}"

def get_trailer_thumbnail(title):
    # Placeholder thumbnail + YouTube search link
    query = title.replace(" ", "+") + "+official+trailer"
    thumb_url = "https://img.youtube.com/vi/dQw4w9WgXcQ/0.jpg"  # sample thumbnail
    trailer_url = f"https://www.youtube.com/results?search_query={query}"
    return thumb_url, trailer_url

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def get_favorites_recommendations(favorites, movies_df):
    if not favorites:
        return pd.DataFrame()  # no favorites yet

    # Convert genres text into numeric vectors
    tfidf = TfidfVectorizer(stop_words="english")
    tfidf_matrix = tfidf.fit_transform(movies_df["genres"].fillna(""))

    # Compute cosine similarity between all movies
    similarities = cosine_similarity(tfidf_matrix, tfidf_matrix)

    # Map titles to indices
    indices = pd.Series(movies_df.index, index=movies_df["title"]).drop_duplicates()

    # Get indices of favorite movies
    fav_indices = [indices[fav] for fav in favorites if fav in indices]

    if not fav_indices:
        return pd.DataFrame()  # no valid favorites found

    # Average similarity scores across favorites
    avg_sim = similarities[fav_indices].mean(axis=0)

    # Sort by similarity
    similar_indices = avg_sim.argsort()[::-1]

    # Exclude already saved favorites
    recommended = movies_df.iloc[similar_indices]
    recommended = recommended[~recommended["title"].isin(favorites)]

    return recommended.head(6)


# 📄 Function to generate PDF
def generate_pdf(similar_movies, collab_titles, hybrid_titles):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="RecommendAI - Movie Recommendations", ln=True, align="C")
    pdf.ln(10)

    def draw_table(title, dataframe, columns):
        pdf.set_font("Arial", 'B', 14)
        pdf.cell(200, 10, txt=title, ln=True)
        pdf.set_font("Arial", 'B', 12)
        pdf.set_fill_color(230, 230, 230)
        col_widths = [90, 90]
        for col in columns:
            pdf.cell(col_widths[columns.index(col)], 8, col.capitalize(), border=1, fill=True)
        pdf.ln(8)
        pdf.set_font("Arial", '', 11)
        for _, row in dataframe.iterrows():
            pdf.cell(col_widths[0], 8, str(row[columns[0]])[:45], border=1)
            pdf.cell(col_widths[1], 8, str(row[columns[1]])[:45], border=1)
            pdf.ln(8)
        pdf.ln(5)

    draw_table("Content-Based Recommendations", similar_movies[["title", "genres"]], ["title", "genres"])
    collab_titles = collab_titles.assign(genres="N/A")
    draw_table("Collaborative Recommendations", collab_titles[["title", "genres"]], ["title", "genres"])
    hybrid_titles = hybrid_titles.assign(genres="N/A")
    draw_table("Hybrid Recommendations", hybrid_titles[["title", "genres"]], ["title", "genres"])

    pdf.set_y(-15)
    pdf.set_font("Arial", 'I', 10)
    pdf.cell(0, 10, f"Generated by RecommendAI - Page {pdf.page_no()}", 0, 0, 'C')

    pdf_bytes = pdf.output(dest="S").encode("latin-1") if isinstance(pdf.output(dest="S"), str) else bytes(pdf.output(dest="S"))
    return pdf_bytes

# 🔄 Real Recommendation Engine (cosine similarity on genres)
def recommend(movie_title, df, top_n=5):
    tfidf = TfidfVectorizer(stop_words="english")
    tfidf_matrix = tfidf.fit_transform(df["genres"].fillna(""))

    cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
    indices = pd.Series(df.index, index=df["title"]).drop_duplicates()
    idx = indices[movie_title]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:top_n+1]

    movie_indices = [i[0] for i in sim_scores]
    return df["title"].iloc[movie_indices].tolist()

# 🖥️ Streamlit UI
st.set_page_config(page_title="RecommendAI", layout="wide")
# st.title("🎬 RecommendAI - Movie Recommendations")
st.markdown("""
<style>
.navbar {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    display: flex;
    justify-content: space-between;
    align-items: center;
    background-color: #111;
    padding: 12px 24px;
    border-bottom: 1px solid #333;
    z-index: 9999;
}
.navbar h2 {
    color: #E50914;
    margin: 0;
    font-weight: 700;
}
</style>
""", unsafe_allow_html=True)

# Navbar container
st.markdown("<div class='navbar'><h2>🎬 RecommendAI</h2>", unsafe_allow_html=True)
st.markdown("""
<style>
.hero {
    margin-top: 80px;  /* pushes hero below navbar */
    background: linear-gradient(180deg, rgba(0,0,0,0.85) 0%, rgba(0,0,0,0.95) 100%),
                url('https://images.unsplash.com/photo-1524985069026-dd778a71c7b4');
    background-size: cover;
    background-position: center;
    border-radius: 12px;
    padding: 3em 2em;
    margin-bottom: 2em;
    box-shadow: 0 0 25px rgba(0,0,0,0.6);
}
.hero h1 {
    color: #ffffff;
    font-size: 2.8em;
    font-weight: 700;
    letter-spacing: 1px;
    text-shadow: 0 0 15px rgba(229,9,20,0.8);
}
.hero p {
    color: #f5f5f5;
    font-size: 1.2em;
    margin-top: 0.5em;
    font-weight: 400;
}
</style>
""", unsafe_allow_html=True)




# 🖼️ Hero Banner HTML
st.markdown("""
<div class="hero">
    <h1>🎬 RecommendAI</h1>
    <p>Your personal cinematic universe — discover, save, and explore movies you’ll love.</p>
</div>
""", unsafe_allow_html=True)

# 🌟 Premium UI Styling
st.markdown("""
<style>
/* Global background and text */
body, .stApp {
    background-color: #0b0b0b;
    color: #f5f5f5;
    font-family: 'Poppins', sans-serif;
}

/* Headings */
h1, h2, h3, h4 {
    color: #ffffff;
    font-weight: 600;
    letter-spacing: 0.5px;
}

/* Tabs */
.css-1h7lk7z, .stTabs [role="tablist"] {
    border-bottom: 2px solid #222;
}
.stTabs [role="tab"] {
    color: #bbb;
    font-weight: 500;
    padding: 0.6em 1.2em;
    border-radius: 8px 8px 0 0;
    transition: all 0.3s ease;
}
.stTabs [role="tab"]:hover {
    color: #fff;
    background-color: #1a1a1a;
}
.stTabs [aria-selected="true"] {
    color: #fff;
    background-color: #E50914;
    font-weight: 600;
}

/* Buttons */
.stButton>button {
    background: linear-gradient(90deg, #E50914 0%, #B20710 100%);
    color: white;
    border: none;
    border-radius: 8px;
    padding: 0.6em 1.2em;
    font-weight: 600;
    box-shadow: 0 0 10px rgba(229,9,20,0.4);
    transition: all 0.3s ease;
}
.stButton>button:hover {
    transform: scale(1.05);
    box-shadow: 0 0 20px rgba(229,9,20,0.6);
}

/* Download buttons */
.stDownloadButton>button {
    background: linear-gradient(90deg, #1DB954 0%, #14833b 100%);
    color: white;
    border-radius: 8px;
    font-weight: 600;
    box-shadow: 0 0 10px rgba(29,185,84,0.4);
}
.stDownloadButton>button:hover {
    transform: scale(1.05);
    box-shadow: 0 0 20px rgba(29,185,84,0.6);
}

/* Sidebar */
.css-1d391kg, .stSidebar {
    background-color: #141414 !important;
    color: #f5f5f5;
}
.stSidebar h2, .stSidebar h3 {
    color: #E50914;
}

/* Movie cards */
img {
    border-radius: 10px;
    box-shadow: 0 0 15px rgba(255,255,255,0.1);
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
/* Reduce vertical spacing between movie cards */
div[data-testid="column"] {
    margin-bottom: -40px !important;   /* tighter spacing */
    padding-left: 5px !important;
    padding-right: 5px !important;
}

/* Center posters and add hover zoom */
img {
    display: block;
    margin: auto;
    border-radius: 12px;
    box-shadow: 0 0 20px rgba(255,255,255,0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}
img:hover {
    transform: scale(1.08);
    box-shadow: 0 0 40px rgba(229,9,20,0.6);
}

/* Adjust subheader spacing */
h4 {
    text-align: center;
    margin-top: 8px;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
.stButton>button {
    display: block;
    margin: 0.5em auto;  /* centers buttons horizontally */
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
/* Center all buttons under posters */
div[data-testid="column"] {
    display: flex;
    flex-direction: column;
    align-items: center;
}

/* Ensure both buttons stack neatly and stay centered */
.stButton>button {
    display: block;
    margin: 0.6em auto;  /* centers horizontally */
    text-align: center;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
/* Center poster titles and ratings perfectly under each image */
div[data-testid="column"] {
    display: flex;
    flex-direction: column;
    align-items: center;
}
h4, p {
    text-align: center !important;
    width: 100%;
}
.stButton>button {
    display: block;
    margin: 0.6em auto;
}
</style>
""", unsafe_allow_html=True)


st.markdown("""
<style>
/* Center buttons perfectly under posters */
.stButton>button {
    display: block;
    margin: 0.6em auto;
    text-align: center;
}

/* Keep both buttons stacked and centered */
div[data-testid="column"] > div {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
/* Slide‑in animation for buttons */
@keyframes slideInLeft {
    from {
        transform: translateX(-40px);
        opacity: 0;
    }
    to {
        transform: translateX(0);
        opacity: 1;
    }
}

.stButton>button {
    display: block;
    margin: 0.6em auto;
    text-align: center;
    animation: slideInLeft 0.5s ease forwards;
}
</style>
""", unsafe_allow_html=True)


st.markdown("""
<style>
/* Highlight Favorites Section */
div[data-testid="stSidebar"] .stSidebar .stSubheader {
    color: #E50914 !important;  /* Netflix red for the subheader */
}

div[data-testid="stSidebar"] {
    border: 2px solid #E50914;  /* red border around sidebar */
    border-radius: 8px;
    padding: 8px;
}
</style>
""", unsafe_allow_html=True)


# Sidebar setup
st.sidebar.title("🎬 RecommendAI Settings")
st.sidebar.markdown("**Customize Your Recommendations**")
# Sample data
similar_movies = pd.DataFrame({
    "title": ["Toy Story", "Aladdin", "Sword in the Stone", "Avengers", "Iron Man"],
    "genres": ["Animation Children", "Animation Comedy", "Animation Children", "Action Sci-Fi", "Action Adventure"]
})
collab_titles = pd.DataFrame({"title": ["Usual Suspects", "Star Wars", "Empire Strikes Back"]})
hybrid_titles = pd.DataFrame({"title": ["Aliens", "Raiders of the Lost Ark", "Silence of the Lambs"]})

# Combine all movies into one DataFrame for favorites-based recommendations
movies_df = pd.concat([
    similar_movies,
    collab_titles.assign(genres="N/A"),
    hybrid_titles.assign(genres="N/A")
])

# Responsive grid function with ratings + favorites + trailer button
def display_movie_grid(df, section_title, section_id="default"):
    st.subheader(section_title)
    if df.empty:
        st.warning("No movies found for this genre. Showing all instead.")
        df = similar_movies

    cols_per_row = 3
    cols = st.columns(cols_per_row)

    for i, (_, row) in enumerate(df.iterrows()):
        col = cols[i % cols_per_row]
        with col:
            poster_url, imdb_rating, rt_rating, plot, director, runtime = get_movie_data(row["title"])

            # ✅ Poster
            if poster_url and poster_url != "N/A":
                st.image(poster_url, width=260)

            # 🎬 Metadata block (title, ratings, director, runtime, plot)
            st.markdown(
                f"""
                <div style='text-align:center; width:260px;'>
                    <h4 style='margin-top:12px; margin-bottom:6px; color:#fff; font-weight:600;'>{row['title']}</h4>
                    <p style='color:#ccc; font-size:15px; margin:0;'>⭐ IMDb: {imdb_rating} &nbsp;&nbsp; 🍅 RT: {rt_rating}</p>
                    <p style='color:#aaa; font-size:14px; margin:4px 0;'>🎬 Director: {director}</p>
                    <p style='color:#aaa; font-size:14px; margin:4px 0;'>⏱ Runtime: {runtime}</p>
                    <p style='color:#ddd; font-size:13px; margin-top:6px;'>{plot[:120]}...</p>
                </div>
                """,
                unsafe_allow_html=True
            )

            # ❤️ Save button
            if st.button(f"❤️ Save {row['title']}", key=f"fav_{row['title']}_{section_id}_{i}"):
                st.session_state["favorites"].append(row["title"])

            # 🎞 Trailer thumbnail + button
            thumb_url, trailer_url = get_trailer_thumbnail(row["title"])
            st.image(thumb_url, width=260, caption="Trailer Preview")

            if st.button(f"▶️ Watch Trailer for {row['title']}", key=f"trailer_{row['title']}_{section_id}_{i}"):
                st.markdown(f"[🎥 Click to open trailer]({trailer_url})", unsafe_allow_html=True)

# ✅ Generate export data early so sidebar can use it
pdf_bytes = generate_pdf(similar_movies, collab_titles, hybrid_titles)
combined = pd.concat([
    similar_movies,
    collab_titles.assign(genres="N/A"),
    hybrid_titles.assign(genres="N/A")
])
csv_bytes = combined.to_csv(index=False).encode("utf-8")
# 📥 Download buttons inside sidebar
st.sidebar.download_button(
    label="⬇️ Download Recommendations as PDF",
    data=pdf_bytes,
    file_name="recommendations.pdf",
    mime="application/pdf"
)

st.sidebar.download_button(
    label="⬇️ Download Recommendations as CSV",
    data=csv_bytes,
    file_name="recommendations.csv",
    mime="text/csv"
)

st.markdown("""
<style>
/* Hover glow for movie cards */
div[data-testid="column"] {
    transition: box-shadow 0.3s ease, transform 0.3s ease;
}
div[data-testid="column"]:hover {
    box-shadow: 0 0 25px rgba(229,9,20,0.6);
    transform: scale(1.03);
}
</style>
""", unsafe_allow_html=True)

filter_option = st.sidebar.selectbox(
    "Filter by Genre",
    ["All", "Action", "Comedy", "Drama", "Animation", "Sci-Fi"]
)



export_option = st.sidebar.radio(
    "Export Format",
    ["PDF", "CSV"]
)

# 🔍 Autocomplete search bar
search_input = st.sidebar.text_input("Search a movie")
suggestions = get_movie_suggestions(search_input) if search_input else []
selected_title = st.sidebar.selectbox("Suggestions", suggestions) if suggestions else None

st.sidebar.markdown("---")
st.sidebar.info("Use the sidebar to adjust filters, search, or export options.")

# ⭐ Favorites list in sidebar (collapsible + export)
with st.sidebar.expander("⭐ Your Favorites", expanded=True):
    if st.session_state["favorites"]:
        for fav in st.session_state["favorites"]:
            st.write("🎬", fav)

        if st.button("🗑️ Clear Favorites"):
            st.session_state["favorites"] = []
            st.success("Favorites cleared!")

        # 📥 Export favorites as CSV
        favs_df = pd.DataFrame({"title": st.session_state["favorites"]})
        st.download_button(
            label="⬇️ Download Favorites as CSV",
            data=favs_df.to_csv(index=False).encode("utf-8"),
            file_name="favorites.csv",
            mime="text/csv"
        )

        # 📄 Export favorites as PDF (styled with red header + table)
        pdf = FPDF()
        pdf.add_page()

        pdf.set_font("Arial", 'B', 16)

        # Red header bar
        pdf.set_fill_color(229, 9, 20)  # Netflix red
        pdf.set_text_color(255, 255, 255)
        pdf.cell(200, 12, txt="Your Favorite Movies", ln=True, align="C", fill=True)
        pdf.ln(10)

        # Reset text color for table
        pdf.set_text_color(0, 0, 0)
        pdf.set_font("Arial", '', 12)

        # Table layout
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(180, 10, "Movie Title", border=1, fill=True, align="C")
        pdf.ln(10)

        for fav in st.session_state["favorites"]:
            pdf.cell(180, 10, fav, border=1, ln=True)

        pdf_bytes = pdf.output(dest="S").encode("latin-1") if isinstance(pdf.output(dest="S"), str) else bytes(pdf.output(dest="S"))

        st.download_button(
            label="⬇️ Download Favorites as PDF",
            data=pdf_bytes,
            file_name="favorites.pdf",
            mime="application/pdf"
        )
    else:
        st.info("No favorites yet. Save some movies!")

# 🎯 Recommended Based on Favorites
if st.session_state["favorites"]:
    st.subheader("🎯 Recommended Based on Your Favorites")
    fav_recs = get_favorites_recommendations(st.session_state["favorites"], movies_df)
    display_movie_grid(fav_recs, "Because you liked these...", section_id="favorites")

# ---------------- NAVBAR ----------------
# 🧩 Navbar fully removed — no header bar or hidden layer remains
st.markdown("""
<style>
.navbar {
    display: none !important;  /* hides the entire navbar container */
}
.hero {
    margin-top: 0px !important;  /* removes extra space that was reserved for navbar */
}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
.hero {
    margin-top: -25px !important;     /* pulls hero right up */
    margin-bottom: -55px !important;  /* eliminates space below hero */
    padding: 0.5em 0.8em !important;  /* minimal internal padding */
}

/* Force Streamlit blocks to collapse spacing */
section.main > div {
    padding-top: 0px !important;
    padding-bottom: 0px !important;
    margin-top: -15px !important;
    margin-bottom: -15px !important;
    line-height: 1.2 !important;      /* tighter text spacing */
}
</style>
""", unsafe_allow_html=True)




# ---------------- END NAVBAR ----------------

# Apply filter safely
filtered_movies = similar_movies if filter_option == "All" else similar_movies[similar_movies["genres"].str.contains(filter_option, case=False, na=False)]


# 🎬 Tabbed layout for recommendations
tab1, tab2, tab3 = st.tabs(["🎬 Content-Based", "🤝 Collaborative", "⚙️ Hybrid"])
with tab1:
    display_movie_grid(filtered_movies, "Content-Based Recommendations", section_id="content")
with tab2:
    display_movie_grid(collab_titles, "Collaborative Recommendations", section_id="collab")
with tab3:
    display_movie_grid(hybrid_titles, "Hybrid Recommendations", section_id="hybrid")


# 🔍 Show search results grid if user typed something
if search_input:
    st.subheader("Search Results")
    results = get_movie_suggestions(search_input)
    if results:
        cols = st.columns(2)
        for i, title in enumerate(results):
            col = cols[i % 2]
            with col:
                poster_url, imdb_rating, rt_rating, plot, director, runtime = get_movie_data(title)

                if poster_url and poster_url != "N/A":
                    st.image(poster_url, width=320)

                st.markdown(
                    f"""
                    <div style='text-align:center; width:320px;'>
                        <h4 style='margin-top:12px; margin-bottom:6px; color:#fff; font-weight:600;'>{title}</h4>
                        <p style='color:#ccc; font-size:15px; margin:0;'>⭐ IMDb: {imdb_rating} &nbsp;&nbsp; 🍅 RT: {rt_rating}</p>
                        <p style='color:#aaa; font-size:14px; margin:4px 0;'>🎬 Director: {director}</p>
                        <p style='color:#aaa; font-size:14px; margin:4px 0;'>⏱ Runtime: {runtime}</p>
                        <p style='color:#ddd; font-size:13px; margin-top:6px;'>{plot}</p>
                    </div>
                    """,
                    unsafe_allow_html=True
                )

                if st.button(f"❤️ Save {title}", key=f"fav_{title}_{i}"):
                    st.session_state["favorites"].append(title)

                trailer_url = get_trailer_link(title)
                if st.button(f"▶️ Watch Trailer for {title}", key=f"trailer_{title}_{i}"):
                    st.markdown(f"[🎥 Click to open trailer]({trailer_url})", unsafe_allow_html=True)

                    # 🔄 Smart Recommendations Section
st.subheader("🔄 Smart Recommendations (Cosine Similarity)")
movie_choice = st.selectbox("Choose a movie for smart recommendations:", similar_movies["title"].values)
if st.button("Get Smart Recommendations"):
    recs = recommend(movie_choice, similar_movies)
    st.write("Recommended movies:")
    for r in recs:
        st.write("🎬", r)

# 📥 Export Recommendations
st.subheader("📥 Export Your Recommendations")
if export_option == "PDF":
    pdf_bytes = generate_pdf(similar_movies, collab_titles, hybrid_titles)
  
elif export_option == "CSV":
    combined = pd.concat([
        similar_movies,
        collab_titles.assign(genres="N/A"),
        hybrid_titles.assign(genres="N/A")
    ])
    csv_bytes = combined.to_csv(index=False).encode("utf-8")
    st.download_button(
        label="📊 Download Recommendations as CSV",
        data=csv_bytes,
        file_name="recommendations.csv",
        mime="text/csv"
    )


